export type Currency = { iso: string; symbol: string; name: string };

export const CURRENCIES: Currency[] = [
  { iso: 'AED', symbol: 'د.إ', name: 'United Arab Emirates Dirham' },
  { iso: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
  { iso: 'ALL', symbol: 'L', name: 'Albanian Lek' },
  { iso: 'AMD', symbol: '֏', name: 'Armenian Dram' },
  { iso: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder' },
  { iso: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza' },
  { iso: 'ARS', symbol: '$', name: 'Argentine Peso' },
  { iso: 'AUD', symbol: '$', name: 'Australian Dollar' },
  { iso: 'AWG', symbol: 'ƒ', name: 'Aruban Florin' },
  { iso: 'AZN', symbol: '₼', name: 'Azerbaijani Manat' },
  { iso: 'BAM', symbol: 'КМ', name: 'Bosnia-Herzegovina Convertible Mark' },
  { iso: 'BBD', symbol: '$', name: 'Barbadian Dollar' },
  { iso: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { iso: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
  { iso: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar' },
  { iso: 'BIF', symbol: 'FBu', name: 'Burundian Franc' },
  { iso: 'BMD', symbol: '$', name: 'Bermudian Dollar' },
  { iso: 'BND', symbol: '$', name: 'Brunei Dollar' },
  { iso: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano' },
  { iso: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { iso: 'BSD', symbol: '$', name: 'Bahamian Dollar' },
  { iso: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
  { iso: 'BWP', symbol: 'P', name: 'Botswana Pula' },
  { iso: 'BYN', symbol: 'Br', name: 'Belarusian Ruble' },
  { iso: 'BZD', symbol: '$', name: 'Belize Dollar' },
  { iso: 'CAD', symbol: '$', name: 'Canadian Dollar' },
  { iso: 'CDF', symbol: 'FC', name: 'Congolese Franc' },
  { iso: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  { iso: 'CLP', symbol: '$', name: 'Chilean Peso' },
  { iso: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  { iso: 'COP', symbol: '$', name: 'Colombian Peso' },
  { iso: 'CRC', symbol: '₡', name: 'Costa Rican Colón' },
  { iso: 'CUP', symbol: '₱', name: 'Cuban Peso' },
  { iso: 'CVE', symbol: '$', name: 'Cape Verdean Escudo' },
  { iso: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  { iso: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc' },
  { iso: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  { iso: 'DOP', symbol: 'RD$', name: 'Dominican Peso' },
  { iso: 'DZD', symbol: 'دج', name: 'Algerian Dinar' },
  { iso: 'EGP', symbol: '£', name: 'Egyptian Pound' },
  { iso: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa' },
  { iso: 'ETB', symbol: 'Br', name: 'Ethiopian Birr' },
  { iso: 'EUR', symbol: '€', name: 'Euro' },
  { iso: 'FJD', symbol: '$', name: 'Fijian Dollar' },
  { iso: 'FKP', symbol: '£', name: 'Falkland Islands Pound' },
  { iso: 'FOK', symbol: 'kr', name: 'Fokland Islands Pound' },
  { iso: 'GBP', symbol: '£', name: 'British Pound Sterling' },
  { iso: 'GEL', symbol: '₾', name: 'Georgian Lari' },
  { iso: 'GHS', symbol: '₵', name: 'Ghanaian Cedi' },
  { iso: 'GIP', symbol: '£', name: 'Gibraltar Pound' },
  { iso: 'GMD', symbol: 'D', name: 'Gambian Dalasi' },
  { iso: 'GNF', symbol: 'FG', name: 'Guinean Franc' },
  { iso: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal' },
  { iso: 'GYD', symbol: '$', name: 'Guyanaese Dollar' },
  { iso: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { iso: 'HNL', symbol: 'L', name: 'Honduran Lempira' },
  { iso: 'HRK', symbol: 'kn', name: 'Croatian Kuna' },
  { iso: 'HTG', symbol: 'G', name: 'Haitian Gourde' },
  { iso: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  { iso: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  { iso: 'ILS', symbol: '₪', name: 'Israeli New Shekel' },
  { iso: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { iso: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar' },
  { iso: 'IRR', symbol: '﷼', name: 'Iranian Rial' },
  { iso: 'ISK', symbol: 'kr', name: 'Icelandic Króna' },
  { iso: 'JMD', symbol: 'J$', name: 'Jamaican Dollar' },
  { iso: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar' },
  { iso: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { iso: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  { iso: 'KGS', symbol: 'сом', name: 'Kyrgystani Som' },
  { iso: 'KHR', symbol: '៛', name: 'Cambodian Riel' },
  { iso: 'KID', symbol: '$', name: 'Kidan' },
  { iso: 'KMF', symbol: 'CF', name: 'Comorian Franc' },
  { iso: 'KRW', symbol: '₩', name: 'South Korean Won' },
  { iso: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar' },
  { iso: 'KYD', symbol: '$', name: 'Cayman Islands Dollar' },
  { iso: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
  { iso: 'LAK', symbol: '₭', name: 'Laotian Kip' },
  { iso: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound' },
  { iso: 'LKR', symbol: 'රු', name: 'Sri Lankan Rupee' },
  { iso: 'LRD', symbol: '$', name: 'Liberian Dollar' },
  { iso: 'LSL', symbol: 'L', name: 'Lesotho Loti' },
  { iso: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar' },
  { iso: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham' },
  { iso: 'MDL', symbol: 'MDL', name: 'Moldovan Leu' },
  { iso: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary' },
  { iso: 'MKD', symbol: 'ден', name: 'Macedonian Denar' },
  { iso: 'MMK', symbol: 'Ks', name: 'Myanmar Kyat' },
  { iso: 'MNT', symbol: '₮', name: 'Mongolian Tugrik' },
  { iso: 'MOP', symbol: 'MOP$', name: 'Macanese Pataca' },
  { iso: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya' },
  { iso: 'MUR', symbol: '₨', name: 'Mauritian Rupee' },
  { iso: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  { iso: 'MWK', symbol: 'MK', name: 'Malawian Kwacha' },
  { iso: 'MXN', symbol: '$', name: 'Mexican Peso' },
  { iso: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { iso: 'MZN', symbol: 'MT', name: 'Mozambican Metical' },
  { iso: 'NAD', symbol: '$', name: 'Namibian Dollar' },
  { iso: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { iso: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba' },
  { iso: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  { iso: 'NPR', symbol: '₨', name: 'Nepalese Rupee' },
  { iso: 'NZD', symbol: '$', name: 'New Zealand Dollar' },
  { iso: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial' },
  { iso: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa' },
  { iso: 'PEN', symbol: 'S/.', name: 'Peruvian Sol' },
  { iso: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina' },
  { iso: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  { iso: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  { iso: 'PLN', symbol: 'zł', name: 'Polish Zloty' },
  { iso: 'PYG', symbol: '₲', name: 'Paraguayan Guarani' },
  { iso: 'QAR', symbol: 'ر.ق', name: 'Qatari Rial' },
  { iso: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  { iso: 'USD', symbol: '$', name: 'US Dollar' },
];
